### ISSUE TITLE
524 Error when too many inspections in the feed are returned.

### ISSUE THREAD

**Issue by Strimboli** [SafetyCulture/safetyculture-exporter#465]
**Describe the bug**
For a long look back period, I am getting a "status: 524, err: invalid character 'e' looking for beginning of value". Error. I suspect this is due to the amount of inspections the feed is returning as my code works for a shorter look back period. However, I need to get data from older inspections.

The run works only when a modified_after date of a few days prior is supplied. It is able to capture this data.
The run does not work when no modified_after date is supplied, assuming the whole history, or when the start of our surveys began for these templates of "2024-03-07". 

**To Reproduce**
1. Run through the steps laid out to download and configure for version 18 [here](https://developer.safetyculture.com/docs/safetyculture-exporter-run). 
2. My account email is *@* (`user_b773c479a7514455b902eada4bc381ef`). Apply a modified_after date of '2024-03-07' with template_ids=["template_2f92f99859d642918d46dc22095c8021", "template_c0dd3a839ebc45ef9066ca4f234a856d"]. I can share the YAML privately, GH won't let me attach a YAML.
3. Attaching the error logs here. 
[Safety Culture Exporter Issue log.log](https://github.com/SafetyCulture/safetyculture-exporter/files/15150895/Safety.Culture.Exporter.Issue.log.log)

**Expected behavior**
Previously, we were using the API, but that did not meet our needs and my client preferred the CSV export they were seeing in this format. Notably due to the category field.
In the API, we were able to run through the feed in batches by providing a modified_after AND modified_before date to set a boundary. It appears modified_before is not available in CLI exporter/YAML.
I would expect modified_before to be an acceptable input, or the exporter to be able to batch the feed by dates in the background.

**Screenshots**
![image](https://github.com/SafetyCulture/safetyculture-exporter/assets/24312706/fc6cda34-ed54-4211-8679-3d78e2ab5b70)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Sonoma 14.4

**Comment by BCook98** [comment]
Hi Steven,

Thanks for reaching out. I have responded to you via email as some of the details of this issue relate to the specific setup of your organisation.
